import test from 'node:test'
import assert from 'node:assert/strict'
import { buildCanonicalFactObject, auditFactConsistency, validateLlmsText, extractVisibleFaqs, validateFaqSchema, generateGeoQueries, normalizeBenchmarkEvidence, calculateGeoMetrics, classifyCrawlerPolicy, aeoGeoScore } from '../services/aeoGeoTruthService.js'

test('canonical AEO facts carry database provenance and generate only supported queries', () => { const facts = buildCanonicalFactObject({ name: 'Welland Chevrolet', address: '1 Main', city: 'Welland', state: 'ON', zip_code: 'L3B', phone: '555', website_url: 'https://dealer.example' }, [{ make: 'Chevrolet', status: 'active' }], { serviceCapabilities: ['repair'], financingCapabilities: ['loans'] }); assert.equal(facts.acceptedFacts[0].sourceType, 'database'); assert.ok(facts.acceptedFacts[0].sourceField); const queries = generateGeoQueries(facts).map(q => q.query); assert.ok(queries.some(q => /Chevrolet dealership/.test(q))); assert.ok(queries.some(q => /service/.test(q))); assert.ok(queries.some(q => /financing/.test(q))) })
test('fact consistency fails only on observed contradictory public evidence', () => { const result = auditFactConsistency({ dealershipName: 'Dealer', phone: '555' }, { dealershipName: { value: 'Other Dealer', sourceUrl: 'https://dealer.example', evidence: { sourceType: 'crawler', verified: true } }, phone: { value: '555', sourceUrl: 'https://dealer.example' } }); assert.equal(result.status, 'fail'); assert.equal(result.checks.find(c => c.field === 'dealershipName').status, 'fail') })
test('llms.txt validates identity and stale/dead facts from real content', () => { const result = validateLlmsText('# Dealer\nPrice 39995\nhttps://dealer.example/old', 'https://dealer.example/llms.txt', { dealershipName: 'Dealer' }, { inventory: [{ vin: 'VIN', price: 39995, status: 'sold' }], deadUrls: ['https://dealer.example/old'] }); assert.equal(result.status, 'fail'); assert.ok(result.findings.some(f => f.type === 'llms_stale_price')); assert.ok(result.findings.some(f => f.type === 'llms_dead_url')) })
test('FAQ schema passes only when visible question and answer exactly match', () => { const visible = extractVisibleFaqs('<details><summary>Do you finance?</summary><p>Yes, ask our team.</p></details>'); const pass = validateFaqSchema(visible, [{ '@type': 'FAQPage', mainEntity: [{ name: 'Do you finance?', acceptedAnswer: { text: 'Yes, ask our team.' } }] }], 'https://dealer.example/faq'); assert.equal(pass.status, 'pass'); const fail = validateFaqSchema(visible, [{ '@type': 'FAQPage', mainEntity: [{ name: 'Do you finance?', acceptedAnswer: { text: 'Different answer.' } }] }], 'https://dealer.example/faq'); assert.equal(fail.status, 'fail') })
test('synthetic GEO evidence is excluded from real citation metrics', () => { const result = calculateGeoMetrics([{ evidenceType: 'synthetic_test', dealershipMentioned: true, dealershipCited: true }, { evidenceType: 'live_ai_response', dealershipMentioned: true, dealershipCited: false, factualAccuracy: false }]); assert.equal(result.queriesTested, 1); assert.equal(result.mentionRate, 100); assert.equal(result.citationRate, 0); assert.equal(result.syntheticRuns, 1) })
test('live benchmark evidence hashes excerpts and preserves unknowns', () => { const record = normalizeBenchmarkEvidence({ query: 'Best dealer', engine: 'Live AI', locale: 'en-CA', evidenceType: 'live_ai_response', responseExcerpt: 'Dealer answer' }); assert.match(record.responseExcerptHash, /^[a-f0-9]{64}$/); assert.equal(record.dealershipCited, null); assert.equal(normalizeBenchmarkEvidence({ evidenceType: 'synthetic_test', query: 'x', engine: 'lab' }).evidenceType, 'synthetic_test') })
test('crawler policy distinguishes retrieval from training and blocking GPTBot is not SEO failure', () => { const robots = { allowed: (url, agent) => agent !== 'gptbot' }; const result = classifyCrawlerPolicy(robots); assert.equal(result.googlebot.category, 'search_or_retrieval'); assert.equal(result.gptbot.category, 'training_or_extended_use'); assert.equal(result.gptbot.allowed, false); assert.equal(aeoGeoScore([{ status: 'pass' }, { status: 'unknown' }]).evidenceCoverage, 50) })
