import test from 'node:test'
import assert from 'node:assert/strict'
import { parsePublicHtml } from '../services/discoverabilityCrawlerService.js'
import { detectAutomotivePage, extractVehicleEntity, validateAutomotiveSchemas, compareInventoryToPublic, calculateFreshnessLag, validateBilingualPages, automotiveScore } from '../services/automotiveDiscoverabilityService.js'
import { auditAutomotiveComponentContracts, websitePublishBlockingIssues } from '../services/websiteDiscoverabilityContracts.js'

const page = (html, url = 'https://dealer.example/vehicle/abc') => ({ finalUrl: url, fetchedAt: '2026-08-29T12:00:00.000Z', html: parsePublicHtml(html, url) })
const vehicleHtml = '<html lang="en-CA"><head><title>2026 GMC Sierra</title><meta name="description" content="Truck"><link rel="canonical" href="https://dealer.example/vehicle/abc"><link rel="alternate" hreflang="fr-CA" href="https://dealer.example/fr/vehicle/abc"></head><body><h1>2026 GMC Sierra AT4</h1><span>1GT12345678901234</span><script type="application/ld+json">{"@context":"https://schema.org","@type":"Vehicle","vehicleIdentificationNumber":"1GT12345678901234","name":"2026 GMC Sierra AT4","brand":{"@type":"Brand","name":"GMC"},"model":"Sierra","offers":{"@type":"Offer","price":44995,"priceCurrency":"CAD","availability":"https://schema.org/InStock"}}</script></body></html>'

test('detects VDPs by Vehicle schema and VIN/content signals', () => { const observed = page(vehicleHtml); const result = detectAutomotivePage(observed); assert.equal(result.pageType, 'vdp'); assert.ok(result.confidence > 0.9); assert.equal(extractVehicleEntity(observed).vin, '1GT12345678901234') })
test('validates actual Vehicle and Offer JSON-LD and catches price mismatch', () => { const observed = page(vehicleHtml); const validation = validateAutomotiveSchemas(observed, { name: 'Dealer' }, [{ vin: '1GT12345678901234', price: 39995 }]); assert.equal(validation.vehicle.status, 'pass'); assert.equal(validation.offer.status, 'fail') })
test('malformed JSON-LD never becomes a schema pass', () => { const observed = page('<html><title>Vehicle</title><body><h1>Vehicle</h1><script type="application/ld+json">{broken</script></body></html>'); const validation = validateAutomotiveSchemas(observed); assert.equal(validation.vehicle.status, 'fail'); assert.ok(validation.parseErrors.length) })
test('compares canonical inventory to public VDPs and flags VIN, price, sold contradictions and missing units', () => { const result = compareInventoryToPublic([{ id: '1', vin: 'EXPECTEDVIN1234567', year: 2024, make: 'GMC', model: 'Sierra', price: 40000, status: 'sold' }, { id: '2', vin: 'MISSINGVIN123456' }], [{ vin: 'WRONGVIN12345678', year: 2024, make: 'GMC', model: 'Sierra', price: 45000, availability: 'InStock', url: 'https://dealer.example/vehicle/abc', sourceUrl: 'https://dealer.example/vehicle/abc' }]); assert.ok(result.findings.some(f => f.type === 'missing_vdp')); assert.ok(result.findings.some(f => f.type === 'public_vdp_without_inventory_record')) })
test('freshness lag is measured only from real timestamps', () => { assert.deepEqual(calculateFreshnessLag('2026-08-29T12:00:00Z', '2026-08-29T12:02:11Z').lagSeconds, 131); assert.equal(calculateFreshnessLag(null, '2026-08-29T12:02:11Z'), null) })
test('bilingual validation is not applicable for monolingual sites and catches non-reciprocal links', () => { assert.equal(validateBilingualPages([{ finalUrl: 'https://dealer.example', language: 'en-CA', hreflang: [] }]).status, 'not_applicable'); assert.equal(validateBilingualPages([{ finalUrl: 'https://dealer.example', language: 'en-CA', hreflang: [{ lang: 'fr-CA', href: 'https://dealer.example/fr' }] }, { finalUrl: 'https://dealer.example/fr', language: 'fr-CA', hreflang: [] }]).status, 'fail') })
test('automotive score exposes weights and unknown coverage', () => { const score = automotiveScore([{ status: 'pass' }, { status: 'unknown' }]); assert.equal(score.qualityScore, 100); assert.equal(score.evidenceCoverage, 50); assert.ok(score.weights.vdpHealth) })
test('Website Builder automotive contracts block severe unbound VDP components but allow ordinary warnings', () => { const blocked = auditAutomotiveComponentContracts({ sections: [{ id: 'v', type: 'vehicle_detail', settings: {} }] }, { name: 'Dealer', address: '1 Main', phone: '555' }); assert.equal(blocked.status, 'fail'); assert.equal(websitePublishBlockingIssues({ issues: blocked.issues }).length, 3); const warning = auditAutomotiveComponentContracts({ sections: [{ id: 's', type: 'service_cta', settings: {} }] }, { name: 'Dealer', address: '1 Main', phone: '555' }); assert.equal(warning.status, 'warn'); assert.equal(websitePublishBlockingIssues({ issues: warning.issues }).length, 0) })
