import test from 'node:test'
import assert from 'node:assert/strict'
import { disconnectedGbpProvider, buildCanonicalLocalEntity, normalizeGbpEvidence, compareGbpToCanonical, compareHours, normalizeLocalRankEvidence, generateLocalQueries, auditLocalPage, localScore, classifyLocalRecommendation } from '../services/localDiscoverabilityService.js'

test('GBP disconnected state contains no synthetic performance or review data', () => { const result = disconnectedGbpProvider(); assert.equal(result.status, 'not_connected'); assert.equal(result.performance.calls, null); assert.equal(result.reviews.averageRating, null) })
test('canonical local entity preserves provenance and does not infer coordinates', () => { const entity = buildCanonicalLocalEntity({ id: 'd1', name: 'Dealer', city: 'Welland', province: 'ON' }); assert.equal(entity.name.sourceType, 'database'); assert.equal(entity.latitude.value, null); assert.equal(entity.address.city.value, 'Welland') })
test('GBP NAP mismatch is evidence-backed and phone mismatch is high severity', () => { const entity = buildCanonicalLocalEntity({ name: 'Dealer', phone: '555', address: '1 Main', city: 'Welland', province: 'ON', postal_code: 'L3B' }); const gbp = normalizeGbpEvidence({ connected: true, business: { name: 'Dealer', phone: '999', address: { street: '1 Main', city: 'Welland', region: 'ON', postalCode: 'L3B' } } }); const result = compareGbpToCanonical(entity, gbp); assert.equal(result.status, 'fail'); assert.equal(result.checks.find(item => item.field === 'phone').severity, 'high') })
test('hours unknown is not a failure and conflicting hours fail', () => { assert.equal(compareHours({ monday: '9-5' }, null).status, 'unknown'); assert.equal(compareHours({ monday: '9-5' }, { monday: 'closed' }).status, 'fail') })
test('local ranks never fabricate values for synthetic tests', () => { const result = normalizeLocalRankEvidence({ evidenceType: 'synthetic_test', query: 'dealer welland', localPackPosition: 1 }); assert.equal(result.status, 'synthetic_test'); assert.equal(result.localPackPosition, null) })
test('local query generation uses actual brands and departments', () => { const entity = buildCanonicalLocalEntity({ city: 'Welland' }, { brands: ['Chevrolet'], departments: ['service', 'parts'] }); const queries = generateLocalQueries(entity); assert.ok(queries.includes('Chevrolet service Welland')); assert.ok(queries.includes('auto parts Welland')); assert.ok(!queries.some(query => /collision/i.test(query))) })
test('local page quality requires local context plus a usable contact or directions action', () => { const entity = buildCanonicalLocalEntity({ city: 'Welland' }); assert.equal(auditLocalPage({ visibleText: 'Visit us in Welland. Call 555-555-5555.' }, entity).status, 'pass'); assert.equal(auditLocalPage({ visibleText: 'Best cars anywhere.' }, entity).status, 'fail') })
test('local quality and evidence coverage stay separate', () => { const result = localScore([{ status: 'pass' }, { status: 'unknown' }, { status: 'fail' }]); assert.equal(result.qualityScore, 50); assert.equal(result.evidenceCoverage, 67); assert.equal(result.verified100, false) })
test('address and hours changes require approval while safe formatting can auto-fix', () => { assert.equal(classifyLocalRecommendation('address_change').executionClass, 'approval_required'); assert.equal(classifyLocalRecommendation('schema_formatting').executionClass, 'auto_fixable') })
