import test from 'node:test'
import assert from 'node:assert/strict'
import { normalizeSxoEvent, classifySource, stitchFirstPartySession, attributionForEvents, funnelFromEvents, conversionRate, roiSummary, sxoQuality, prioritizeSxoRecommendation } from '../services/sxoAttributionService.js'

const event = (eventType, extra = {}) => normalizeSxoEvent({ eventType, dealershipId: 'd1', created_at: '2026-08-29T12:00:00Z', ...extra })

test('source classification keeps unknown traffic unknown and recognizes search, AI, GBP, and direct', () => { assert.equal(classifySource({ referrer: 'https://www.google.com/search?q=x', medium: 'organic' }), 'google_organic'); assert.equal(classifySource({ referrer: 'https://chatgpt.com/', medium: 'referral' }), 'ai_search'); assert.equal(classifySource({ source: 'gbp' }), 'google_business_profile'); assert.equal(classifySource({}), 'direct'); assert.equal(classifySource({ source: 'mystery' }), 'unknown') })
test('first-party session stitching is dealership scoped and does not fingerprint', () => { const result = stitchFirstPartySession([event('vdp_view', { anonymousSessionId: 's1' }), event('page_view', { anonymousSessionId: 's1', dealershipId: 'd2' })], { sessionId: 's1', contactId: 'c1', dealershipId: 'd1' }); assert.equal(result.linked.length, 1); assert.equal(result.linked[0].contactId, 'c1'); assert.equal(stitchFirstPartySession([], { sessionId: 's1', contactId: null, dealershipId: 'd1' }).status, 'unknown') })
test('funnel counts only recognized real events and leaves absent stages measurable as zero', () => { const result = funnelFromEvents([event('landing_page_view'), event('vdp_view'), event('lead_created')]); assert.equal(result.landing_page_view.count, 1); assert.equal(result.vdp_view.count, 1); assert.equal(result.deal_sold.count, 0) })
test('conversion rates require a denominator', () => { assert.equal(conversionRate(4, 0).rate, null); assert.deepEqual(conversionRate(4, 100), { rate: 4, numerator: 4, denominator: 100, status: 'measured' }) })
test('first-touch, last-touch and assisted attribution remain explicit', () => { const events = [event('landing_page_view', { contactId: 'c1', source: 'google', medium: 'organic', occurredAt: '2026-08-28T12:00:00Z' }), event('lead_created', { contactId: 'c1', source: 'email', medium: 'email', occurredAt: '2026-08-29T12:00:00Z' })]; assert.equal(attributionForEvents(events, 'first_touch')[0].source, 'google_organic'); assert.equal(attributionForEvents(events, 'last_touch')[0].source, 'email'); assert.equal(attributionForEvents(events, 'assisted')[0].touches.length, 2) })
test('ROI never invents gross and labels unavailable outcomes', () => { const result = roiSummary({ events: [event('lead_created')] }); assert.equal(result.leads, 1); assert.equal(result.attributedGross, null); assert.equal(result.status, 'not_measured') })
test('SXO quality is separate from business performance and unknown coverage', () => { const result = sxoQuality([{ status: 'pass' }, { status: 'unknown' }, { status: 'fail' }]); assert.equal(result.qualityScore, 50); assert.equal(result.evidenceCoverage, 67) })
test('recommendation priority uses proven signals only', () => { const result = prioritizeSxoRecommendation({ sessions: 100, leads: 2, attributedGross: null }); assert.equal(result.priorityScore, 300); assert.equal(result.evidence.gross, 'unavailable') })
