/**
 * MarketSync Customer Intelligence — Barrel Exports.
 */

export * from './customer-intelligence-state.js'
export * from './intent-engine.js'
export * from './journey-engine.js'
export * from './next-best-question.js'
export * from './objection-engine.js'
export * from './lead-scoring.js'
export * from './recommendation-engine.js'
export * from './next-best-action.js'
export * from './ai-tool-orchestrator.js'
export * from './response-verifier.js'
export * from './lead-brief-engine.js'
export * from './handoff-copilot-engine.js'
export * from './continuity-memory-engine.js'
export * from './offline-recovery-engine.js'
export * from './intelligence-events.js'
export * from './conversation-goals.js'
export * from './customer-friction-engine.js'
export * from './customer-constraint-engine.js'
export * from './commercial-intelligence.js'
export * from './decision-map-engine.js'
export * from './identity-attribution-engine.js'
export * from './what-changed-engine.js'
export * from './ownership-state-machine.js'
export * from './knowledge-governance.js'
export * from './demand-analytics.js'
export * from './multi-agent-orchestrator.js'
export * from './policy-engine.js'
export * from './action-utility-engine.js'
export * from './customer-readiness-engine.js'
export * from './objection-root-cause.js'
export * from './question-value-engine.js'
export * from './commitments-tracker.js'
export * from './inventory-watch-engine.js'
export * from './expert-routing-engine.js'
export * from './digital-experience-engine.js'
export * from './incident-governance-engine.js'
export * from './domain-pack-architecture.js'
