import { buildReportPlan, VISUALIZATIONS, COMPARISONS, MAX_DIMENSIONS } from './query-engine.js'
import { getMetric, listMetrics } from './metric-registry.js'
import { listDimensions } from './dimension-registry.js'

export function reportLabCatalog() {
  return {
    metrics: listMetrics().map((m) => ({
      id: m.id, display_name: m.display_name, department: m.department,
      unit: m.unit, allowed_dimensions: m.allowed_dimensions
    })),
    dimensions: listDimensions().map((d) => ({ id: d.id, group: d.group, pii: d.pii })),
    visualizations: [...VISUALIZATIONS],
    comparisons: [...COMPARISONS],
    max_dimensions: MAX_DIMENSIONS
  }
}

export function compileReportLab(selection = {}) {
  const metricId = selection.metric || selection.metric_id
  const dimensions = [selection.dimension1, selection.dimension2, selection.dimension3, selection.dimension4, selection.dimension5]
    .filter(Boolean)
  const plan = buildReportPlan({
    metric_id: metricId,
    metric_ids: selection.metric_ids || (metricId ? [metricId] : []),
    dimensions,
    filters: selection.filters || {},
    date_range: selection.date_range || { days: selection.days || 30 },
    comparison: selection.compare || selection.comparison || null,
    visualization: selection.visualization || 'table'
  })
  return {
    ok: true,
    definition: {
      id: selection.save_as_id || null,
      name: selection.name || `${getMetric(plan.metric_ids[0])?.display_name || 'Custom'} lab report`,
      description: 'Generated by Report Lab from approved registries.',
      department: getMetric(plan.metric_ids[0])?.department || 'executive',
      metric_ids: plan.metric_ids,
      default_dimensions: plan.dimensions,
      filters: plan.filters,
      date_range: plan.date_range,
      comparison: plan.comparison,
      visualization: plan.visualization,
      drilldowns: plan.dimensions,
      recommended_actions: [],
      permissions: ['reports.view'],
      origin: 'report_lab'
    },
    plan
  }
}
