### Login - run this first
POST https://vehicle-marketplace-s0e4.onrender.com/auth/login
Content-Type: application/json

{"email":"jason@wellandchev.com","password":"Hookups1!"}

### Auth Me
GET https://vehicle-marketplace-s0e4.onrender.com/auth/me
Authorization: Bearer paste-token-here

### Debug
GET https://vehicle-marketplace-s0e4.onrender.com/debug
Authorization: Bearer paste-token-here

### Inventory
GET https://vehicle-marketplace-s0e4.onrender.com/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY0NzU0MjI4LWQ2MWItNDJmMy04Y2MwLWExNDZmM2M0ZjAxNCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL29teXVxenZlZWd6c3Blb2pycWtkLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3OTdjMzQ1MC05ZjE2LTQ3YzYtOTE4YS1jMDI5NDZmMTM4YTciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5MzMwMDIxLCJpYXQiOjE3NzkzMjY0MjEsImVtYWlsIjoiamFzb25Ad2VsbGFuZGNoZXYuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzkzMjY0MjF9XSwic2Vzc2lvbl9pZCI6ImQ2YjQ2NDZj