import crypto from 'node:crypto'
import { supabaseAdmin } from '../shared.js'
import { isFieldProtected } from './recommendationEngine.js'

export const AUTOPILOT_MODES = Object.freeze(['monitor', 'recommend', 'auto_fix'])
export const QUEUE_STATES = Object.freeze(['detected', 'queued', 'awaiting_approval', 'approved', 'applying', 'applied_pending_publish', 'publishing', 'published_pending_validation', 'validating', 'validated', 'validation_failed', 'rollback_pending', 'rolling_back', 'rollback_validated', 'rolled_back', 'manual_required', 'regressed', 'dismissed'])
const now = () => new Date().toISOString()
const id = prefix => `${prefix}_${crypto.randomBytes(8).toString('hex')}`
const number = value => value == null || value === '' || !Number.isFinite(Number(value)) ? null : Number(value)

export function dedupeFingerprint({ dealershipId, pillar, type, url, entityType, entityId, field } = {}) { return [dealershipId, pillar, type, url, entityType, entityId, field].map(value => String(value || '').trim().toLowerCase()).join('|') }

export function normalizeFinding(finding = {}, dealershipId = finding.dealershipId || finding.dealer_id) {
  if (!dealershipId || !finding.type) throw new Error('Finding dealershipId and type are required')
  const affectedUrls = finding.affectedUrls || finding.affected_urls || (finding.sourceUrl ? [finding.sourceUrl] : [])
  const pillar = finding.pillar || 'validation'
  return { id: String(finding.id || id('finding')), dealershipId: String(dealershipId), pillar, category: finding.category || null, type: String(finding.type), severity: finding.severity || 'medium', status: finding.status || 'open', affectedUrls: Array.isArray(affectedUrls) ? affectedUrls : [], entityType: finding.entityType || finding.entity_type || null, entityId: finding.entityId || finding.entity_id || null, sourceType: finding.sourceType || finding.source_type || finding.source || 'unknown', sourceRunId: finding.sourceRunId || finding.source_run_id || null, evidence: finding.evidence || {}, confidence: number(finding.confidence), fingerprint: finding.fingerprint || dedupeFingerprint({ dealershipId, pillar, type: finding.type, url: affectedUrls[0], entityType: finding.entityType, entityId: finding.entityId, field: finding.field }), detectedAt: finding.detectedAt || finding.detected_at || now(), lastObservedAt: finding.lastObservedAt || finding.last_observed_at || now(), resolvedAt: finding.resolvedAt || finding.resolved_at || null }
}

export function normalizeRecommendation(recommendation = {}, findings = []) {
  const validFindings = (Array.isArray(findings) ? findings : [findings]).filter(Boolean).map(finding => normalizeFinding(finding, recommendation.dealershipId || recommendation.dealership_id || finding.dealershipId))
  const findingIds = recommendation.findingIds || recommendation.finding_ids || validFindings.map(finding => finding.id)
  if (!findingIds.length || !validFindings.length) throw new Error('A recommendation requires at least one finding, and it must be valid')
  const first = validFindings[0] || {}; const dealershipId = recommendation.dealershipId || recommendation.dealership_id || first.dealershipId
  if (!dealershipId) throw new Error('Recommendation dealershipId is required')
  const affectedUrls = recommendation.affectedUrls || recommendation.affected_urls || first.affectedUrls || []
  const change = recommendation.recommendedChange || recommendation.recommended_change || {}
  return { id: String(recommendation.id || id('recommendation')), dealershipId: String(dealershipId), findingIds: findingIds.map(String), pillar: recommendation.pillar || first.pillar || 'validation', title: recommendation.title || `Resolve ${first.type || 'discoverability finding'}`, summary: recommendation.summary || '', rationale: recommendation.rationale || null, executionClass: recommendation.executionClass || recommendation.execution_class || 'approval_required', riskLevel: recommendation.riskLevel || recommendation.risk_level || 'medium', confidence: number(recommendation.confidence ?? first.confidence), status: recommendation.status || 'detected', affectedUrls, recommendedChange: change, applyStrategy: recommendation.applyStrategy || recommendation.apply_strategy || null, expectedEvidence: recommendation.expectedEvidence || recommendation.expected_evidence || null, fingerprint: recommendation.fingerprint || dedupeFingerprint({ dealershipId, pillar: recommendation.pillar || first.pillar, type: first.type || recommendation.title, url: affectedUrls[0], entityType: first.entityType, entityId: first.entityId, field: change.field }), createdAt: recommendation.createdAt || recommendation.created_at || now(), approvedAt: recommendation.approvedAt || recommendation.approved_at || null, appliedAt: recommendation.appliedAt || recommendation.applied_at || null, publishedAt: recommendation.publishedAt || recommendation.published_at || null, validatedAt: recommendation.validatedAt || recommendation.validated_at || null }
}

export function classifyRisk(recommendation = {}, { external = false, protectedFields = [] } = {}) {
  if (external) return { executionClass: 'manual', riskLevel: 'high', allowed: false, reason: 'External website has no supported write integration' }
  const change = recommendation.recommendedChange || recommendation.recommended_change || {}; const field = String(change.field || '').toLowerCase(); const protectedField = isFieldProtected(field) || protectedFields.some(value => field === value || field.includes(value))
  if (protectedField) return { executionClass: 'approval_required', riskLevel: 'high', allowed: false, reason: `Protected field '${change.field}' requires explicit approval` }
  if (recommendation.executionClass !== 'auto_fixable' || recommendation.riskLevel !== 'low') return { executionClass: 'approval_required', riskLevel: recommendation.riskLevel || 'medium', allowed: false, reason: 'Change is not low-risk auto-fixable' }
  if (recommendation.confidence == null || recommendation.confidence < 90) return { executionClass: 'approval_required', riskLevel: 'low', allowed: false, reason: 'Confidence is below the 90% automatic-fix threshold' }
  return { executionClass: 'auto_fixable', riskLevel: 'low', allowed: true, reason: 'Low-risk, high-confidence change from measured evidence' }
}
export function riskPolicy(recommendation = {}, options = {}) { return classifyRisk(recommendation, options) }

const transitions = { detected: ['queued', 'awaiting_approval', 'manual_required', 'dismissed'], queued: ['applying', 'awaiting_approval', 'manual_required'], awaiting_approval: ['approved', 'dismissed', 'manual_required'], approved: ['applying', 'manual_required'], applying: ['applied_pending_publish', 'validation_failed'], applied_pending_publish: ['publishing', 'validation_failed'], publishing: ['published_pending_validation', 'validation_failed'], published_pending_validation: ['validating', 'validation_failed'], validating: ['validated', 'validation_failed', 'rollback_pending'], validated: ['regressed', 'rollback_pending'], validation_failed: ['rollback_pending', 'manual_required'], rollback_pending: ['rolling_back', 'manual_required'], rolling_back: ['rollback_validated', 'validation_failed'], rollback_validated: ['rolled_back'], regressed: ['queued', 'rollback_pending'], manual_required: ['external_pending', 'dismissed'], external_pending: ['external_verified', 'manual_required'] }
export function canTransition(from, to) { return Boolean(transitions[from]?.includes(to)) }
export function nextQueueState(item, status, evidence = null) { if (!canTransition(item.status, status)) throw new Error(`Invalid Autopilot transition: ${item.status} -> ${status}`); return { ...item, status, evidence, updatedAt: now() } }
export function initialQueueState(mode, { external = false } = {}) { if (external) return 'manual_required'; if (mode === 'monitor') return 'detected'; return mode === 'auto_fix' ? 'queued' : 'awaiting_approval' }

export function enforceGuardrails({ automaticFixesToday = 0, pagesInBatch = 0, lastAppliedAt = null, nowMs = Date.now(), maxFixesPerDay = 10, maxPagesPerBatch = 25, cooldownMs = 300000, confidence = 100, minimumConfidence = 90 } = {}) { if (automaticFixesToday >= maxFixesPerDay) return { allowed: false, reason: 'Daily automatic-fix limit reached' }; if (pagesInBatch >= maxPagesPerBatch) return { allowed: false, reason: 'Batch page limit reached' }; if (confidence < minimumConfidence) return { allowed: false, reason: `Confidence (${confidence}) is below the minimum ${minimumConfidence}` }; if (lastAppliedAt && nowMs - Date.parse(lastAppliedAt) < cooldownMs) return { allowed: false, reason: 'Resource cooldown is active' }; return { allowed: true, reason: 'Guardrails passed' } }

export function sxoStageEvidence(events = [], instrumentedStages = []) { const stages = {}; const known = new Set(instrumentedStages); for (const stage of ['landing_page_view', 'srp_view', 'vdp_view', 'form_submitted', 'lead_created', 'appointment_created', 'deal_sold', 'vehicle_delivered']) { const count = events.filter(event => event.eventType === stage).length; stages[stage] = known.has(stage) ? { count, status: 'measured_zero' } : { count: null, status: 'not_instrumented' } }; const measured = Object.values(stages).filter(stage => stage.status === 'measured_zero').length; return { stages, evidenceCoverage: Math.round(measured / Object.keys(stages).length * 100) } }
export function joinCanonicalDealRevenue(deal = {}) { const frontGross = number(deal.front_gross ?? deal.frontGross); const backGross = number(deal.back_gross ?? deal.backGross); const totalGross = number(deal.total_gross ?? deal.totalGross); return { dealId: deal.id || deal.deal_id || null, delivered: deal.delivered === true || deal.delivery_status === 'delivered', frontGross, backGross, totalGross, currency: deal.currency || 'CAD', status: totalGross == null && frontGross == null && backGross == null ? 'not_measured' : 'measured', source: 'canonical_dealeros_deal' } }
export function joinCanonicalServiceRevenue(repairOrder = {}) { const revenue = number(repairOrder.total_revenue ?? repairOrder.service_revenue ?? repairOrder.total); return { repairOrderId: repairOrder.id || repairOrder.repair_order_id || null, closed: ['closed', 'completed', 'invoiced'].includes(String(repairOrder.status || '').toLowerCase()), revenue, currency: repairOrder.currency || 'CAD', status: revenue == null ? 'not_measured' : 'measured', source: 'canonical_dealeros_repair_order' } }
export function completeVehicleAttribution(chain = {}) { const complete = Boolean(chain.source && chain.sessionId && chain.contactId && chain.vehicleId && chain.dealId && chain.delivered && chain.grossEvidence); return { complete, confidence: complete ? 'high' : 'unknown', source: complete ? chain.source : null, vehicleId: chain.vehicleId || null, dealId: chain.dealId || null, gross: complete ? number(chain.gross) : null, status: complete ? 'measured' : 'not_measured' } }
export function completeServiceAttribution(chain = {}) { const complete = Boolean(chain.source && chain.sessionId && chain.contactId && chain.appointmentId && chain.repairOrderId && chain.closed && chain.revenueEvidence); return { complete, confidence: complete ? 'high' : 'unknown', source: complete ? chain.source : null, repairOrderId: chain.repairOrderId || null, revenue: complete ? number(chain.revenue) : null, status: complete ? 'measured' : 'not_measured' } }

function findingRow(finding) { return { id: finding.id, dealership_id: finding.dealershipId, pillar: finding.pillar, category: finding.category, type: finding.type, severity: finding.severity, status: finding.status, affected_urls: finding.affectedUrls, entity_type: finding.entityType, entity_id: finding.entityId, source_type: finding.sourceType, source_run_id: finding.sourceRunId, evidence: finding.evidence, confidence: finding.confidence, fingerprint: finding.fingerprint, detected_at: finding.detectedAt, last_observed_at: finding.lastObservedAt, resolved_at: finding.resolvedAt } }
export async function persistFinding(finding) { const normalized = normalizeFinding(finding); const { data, error } = await supabaseAdmin.from('discoverability_findings').upsert(findingRow(normalized), { onConflict: 'dealership_id,fingerprint' }).select('*').single(); if (error) throw error; return data }
export async function persistRecommendation(recommendation, findings = []) { const normalized = normalizeRecommendation(recommendation, findings); const row = { id: normalized.id, dealership_id: normalized.dealershipId, finding_ids: normalized.findingIds, pillar: normalized.pillar, title: normalized.title, summary: normalized.summary, rationale: normalized.rationale, execution_class: normalized.executionClass, risk_level: normalized.riskLevel, confidence: normalized.confidence, status: normalized.status, affected_urls: normalized.affectedUrls, recommended_change: normalized.recommendedChange, apply_strategy: normalized.applyStrategy, expected_evidence: normalized.expectedEvidence, fingerprint: normalized.fingerprint, created_at: normalized.createdAt, approved_at: normalized.approvedAt, applied_at: normalized.appliedAt, published_at: normalized.publishedAt, validated_at: normalized.validatedAt }; const { data, error } = await supabaseAdmin.from('discoverability_recommendations').upsert(row, { onConflict: 'dealership_id,fingerprint' }).select('*').single(); if (error) throw error; return data }
export async function enqueueRecommendation({ dealershipId, recommendation, findings = [], mode = 'recommend', external = false, idempotencyKey = id('idem') }) { const normalized = normalizeRecommendation({ ...(recommendation || {}), dealershipId: recommendation?.dealershipId || dealershipId }, findings); const policy = classifyRisk(normalized, { external, protectedFields: ['price', 'address', 'phone', 'hours', 'dealership_name', 'delete', 'redirect'] }); const status = external ? 'manual_required' : mode === 'monitor' ? 'detected' : mode === 'auto_fix' && policy.allowed ? 'queued' : 'awaiting_approval'; const { data, error } = await supabaseAdmin.from('discoverability_autopilot_queue').upsert({ dealership_id: normalized.dealershipId, recommendation_id: normalized.id, mode, status, idempotency_key: idempotencyKey, risk_decision: policy, attempts: 0 }, { onConflict: 'dealership_id,idempotency_key' }).select('*').single(); if (error) throw error; return { queue: data, policy, recommendation: normalized } }
export async function transitionQueue({ dealershipId, queueId, to, evidence = null, actorId = null }) { const { data: current, error: readError } = await supabaseAdmin.from('discoverability_autopilot_queue').select('*').eq('id', queueId).eq('dealership_id', dealershipId).single(); if (readError) throw readError; const next = nextQueueState(current, to, evidence); const { data, error } = await supabaseAdmin.from('discoverability_autopilot_queue').update({ status: to, evidence, updated_at: next.updatedAt, attempts: Number(current.attempts || 0) + (to === 'applying' ? 1 : 0) }).eq('id', queueId).eq('dealership_id', dealershipId).eq('status', current.status).select('*').single(); if (error) throw error; await supabaseAdmin.from('discoverability_autopilot_transitions').insert({ queue_id: queueId, dealership_id: dealershipId, from_status: current.status, to_status: to, evidence, actor_id: actorId }); return data }
export async function createValidationJob({ dealershipId, deploymentId = null, revisionId = null, affectedUrls = [], expectedState = {}, recommendationId = null }) { const { data, error } = await supabaseAdmin.from('discoverability_validation_jobs').insert({ dealership_id: dealershipId, deployment_id: deploymentId, revision_id: revisionId, affected_urls: affectedUrls, expected_state: { ...expectedState, recommendationId }, status: 'published_pending_validation' }).select('*').single(); if (error) throw error; return data }
export async function recordValidationResult({ dealershipId, jobId, passed, observedState = null, evidence = null, errorMessage = null }) { const status = passed ? 'validated' : 'validation_failed'; const { data, error } = await supabaseAdmin.from('discoverability_validation_jobs').update({ status, observed_state: observedState, error: errorMessage, completed_at: now() }).eq('id', jobId).eq('dealership_id', dealershipId).select('*').single(); if (error) throw error; return { ...data, evidence, status } }
export async function resolveFindingAfterValidation({ dealershipId, findingId, validationEvidenceId = null, resolved = false }) { const status = resolved ? 'resolved' : 'regressed'; const { data, error } = await supabaseAdmin.from('discoverability_findings').update({ status, resolved_at: resolved ? now() : null, last_observed_at: now(), evidence: { validationEvidenceId } }).eq('id', findingId).eq('dealership_id', dealershipId).select('*').single(); if (error) throw error; return data }
export async function getAutopilotQueue(dealershipId, { status = null, limit = 100 } = {}) { let query = supabaseAdmin.from('discoverability_autopilot_queue').select('*').eq('dealership_id', dealershipId).order('created_at', { ascending: false }).limit(Math.min(Number(limit) || 100, 250)); if (status) query = query.eq('status', status); const { data, error } = await query; if (error) throw error; return data || [] }
export async function getAutopilotAuditTrail(dealershipId, queueId) { const [{ data: queue, error: queueError }, { data: transitions, error: transitionError }] = await Promise.all([supabaseAdmin.from('discoverability_autopilot_queue').select('*, discoverability_recommendations(*)').eq('dealership_id', dealershipId).eq('id', queueId).maybeSingle(), supabaseAdmin.from('discoverability_autopilot_transitions').select('*').eq('dealership_id', dealershipId).eq('queue_id', queueId).order('created_at', { ascending: true })]); if (queueError) throw queueError; if (transitionError) throw transitionError; return { queue, transitions: transitions || [] } }
