import crypto from 'node:crypto'

const n = value => Number.isFinite(Number(value)) ? Number(value) : null
const pct = (current, previous) => previous ? Math.round((current - previous) / Math.abs(previous) * 1000) / 10 : null
const norm = value => String(value || '').trim().toLowerCase()

export const SEARCH_WEIGHTS = Object.freeze({ connectionValidity: 20, metadataExecution: 20, landingPageCoverage: 15, sitemapConsistency: 15, inventoryAlignment: 15, trendHealth: 15 })

export function disconnectedSearchProvider(provider = 'google_search_console') { return { status: 'not_connected', provider, property: null, measuredAt: null, dateRange: null, totals: { clicks: null, impressions: null, ctr: null, position: null }, queries: [], pages: [], queryPagePairs: [] } }

export function verifySearchProperty(websiteUrl, property) { if (!websiteUrl || !property) return { status: 'unknown', websiteUrl: websiteUrl || null, property: property || null, evidence: null }; try { const site = new URL(websiteUrl); const candidate = new URL(property); const match = site.hostname === candidate.hostname && (!property.endsWith('/') ? true : site.pathname.startsWith(candidate.pathname)); return { status: match ? 'pass' : 'fail', websiteUrl, property, evidence: { sourceType: 'search_console', sourceUrl: property, measuredAt: new Date().toISOString(), rawValue: { websiteUrl, property }, verified: true } } } catch { return { status: 'fail', websiteUrl, property, evidence: { sourceType: 'search_console', verified: true, error: 'invalid property URL' } } } }

export function normalizeSearchConsoleResponse(payload = {}, options = {}) { const rows = Array.isArray(payload.rows) ? payload.rows : []; const totals = payload.totals || rows.reduce((acc, row) => ({ clicks: acc.clicks + (n(row.clicks) || 0), impressions: acc.impressions + (n(row.impressions) || 0) }), { clicks: 0, impressions: 0 }); const normalize = row => { const impressions = n(row.impressions); const clicks = n(row.clicks); return { query: row.keys?.[0] || row.query || null, page: row.keys?.[1] || row.page || null, country: row.keys?.[2] || row.country || null, device: row.keys?.[3] || row.device || null, date: row.keys?.[4] || row.date || null, clicks, impressions, ctr: n(row.ctr) ?? (impressions ? clicks / impressions : null), position: n(row.position) } }; const normalized = rows.map(normalize); const queries = aggregateMetrics(normalized, 'query'); const pages = aggregateMetrics(normalized, 'page'); return { status: 'measured', provider: options.provider || 'google_search_console', property: options.property || null, measuredAt: options.fetchedAt || new Date().toISOString(), fetchedAt: options.fetchedAt || new Date().toISOString(), dateRange: options.dateRange || null, totals: { clicks: n(totals.clicks), impressions: n(totals.impressions), ctr: n(totals.ctr) ?? (n(totals.impressions) ? n(totals.clicks) / n(totals.impressions) : null), position: n(totals.position) }, queries, pages, queryPagePairs: normalized }
}

function aggregateMetrics(rows, field) { const grouped = new Map(); for (const row of rows) { const key = row[field]; if (!key) continue; const old = grouped.get(key) || { [field]: key, clicks: 0, impressions: 0, weightedPosition: 0 }; old.clicks += row.clicks || 0; old.impressions += row.impressions || 0; if (row.position != null) old.weightedPosition += row.position * (row.impressions || 1); grouped.set(key, old) } return [...grouped.values()].map(row => ({ [field]: row[field], clicks: row.clicks, impressions: row.impressions, ctr: row.impressions ? row.clicks / row.impressions : null, position: row.impressions ? row.weightedPosition / row.impressions : null })) }

export function compareSearchPeriods(current = {}, previous = {}) { return Object.fromEntries(['clicks', 'impressions', 'ctr', 'position'].map(metric => { const c = n(current[metric]); const p = n(previous[metric]); return [metric, { current: c, previous: p, delta: c == null || p == null ? null : c - p, changePercent: c == null || p == null ? null : pct(c, p) }] })) }

export function detectSearchOpportunities(data = {}, options = {}) { const minImpressions = Number(options.minImpressions ?? 100); const opportunities = []; for (const row of data.queries || []) { if ((row.impressions || 0) < minImpressions) continue; if (row.position != null && row.position >= 8 && row.position <= 20) opportunities.push({ type: 'near_page_one_opportunity', query: row.query, evidence: row, opportunityScore: Math.round(row.impressions * Math.max(0, 21 - row.position)), reason: 'Meaningful Search Console impressions with a page-two position.' }); if (row.ctr != null && row.ctr < Number(options.lowCtr ?? 0.02) && row.position != null && row.position <= 10) opportunities.push({ type: 'high_visibility_low_ctr', query: row.query, evidence: row, opportunityScore: Math.round(row.impressions * (Number(options.lowCtr ?? 0.02) - row.ctr)), reason: 'The query has measurable visibility but a low observed click-through rate.' }) } return opportunities }

export function detectFallingQueries(current = [], previous = [], options = {}) { const minImpressions = Number(options.minImpressions ?? 100); const old = new Map(previous.map(row => [norm(row.query), row])); return current.filter(row => (row.impressions || 0) >= minImpressions).map(row => ({ row, prior: old.get(norm(row.query)) })).filter(item => item.prior && item.row.clicks < item.prior.clicks && (item.prior.clicks - item.row.clicks) / Math.max(item.prior.clicks, 1) >= Number(options.declineRate ?? 0.2)).map(item => ({ type: 'falling_query', query: item.row.query, evidence: { current: item.row, previous: item.prior }, opportunityScore: item.prior.clicks - item.row.clicks })) }

export function detectCannibalization(pairs = [], options = {}) { const threshold = Number(options.minImpressions ?? 100); const grouped = new Map(); for (const pair of pairs) { if ((pair.impressions || 0) < threshold || !pair.query || !pair.page) continue; const list = grouped.get(norm(pair.query)) || []; list.push(pair); grouped.set(norm(pair.query), list) } return [...grouped.entries()].filter(([, rows]) => new Set(rows.map(row => row.page)).size > 1).map(([query, rows]) => ({ type: 'keyword_cannibalization', query, competingPages: rows.map(row => ({ page: row.page, impressions: row.impressions, position: row.position })), impressionShare: rows.map(row => ({ page: row.page, share: rows.reduce((sum, item) => sum + item.impressions, 0) ? row.impressions / rows.reduce((sum, item) => sum + item.impressions, 0) : null })), confidence: Math.min(1, rows.reduce((sum, row) => sum + row.impressions, 0) / 10000), evidence: rows })) }

export function detectContentGaps(queries = [], crawlPages = [], facts = {}) { const text = crawlPages.map(page => `${page.title || ''} ${page.text || ''} ${page.url || ''}`).join(' ').toLowerCase(); const capabilities = [...(facts.serviceCapabilities || []), ...(facts.financingCapabilities || [])].map(norm); return queries.filter(row => (row.impressions || 0) > 0).filter(row => { const q = norm(row.query); const service = /service|repair|brake|maintenance/.test(q); const finance = /finance|financing|credit/.test(q); return (service && capabilities.some(item => /service|repair|maintenance/.test(item)) || finance && capabilities.some(item => /finance|loan|credit/.test(item))) && !text.includes(q) }).map(row => ({ type: 'content_gap', query: row.query, evidence: row, reason: 'Observed search demand matches a canonical dealership capability without a matching useful public page.' })) }

export function detectInventoryDemandGaps(queries = [], inventory = [], pages = []) { const makes = new Set(inventory.map(v => norm(v.make))); const models = new Set(inventory.map(v => norm(v.model))); const text = pages.map(page => `${page.title || ''} ${page.url || ''}`).join(' ').toLowerCase(); return queries.filter(row => (row.impressions || 0) > 0).filter(row => { const q = norm(row.query); return [...makes, ...models].some(term => term && q.includes(term)) && !text.includes(q.replace(/\b(?:for sale|near|in)\b/g, '').trim()) }).map(row => ({ type: 'inventory_search_demand_gap', query: row.query, evidence: row, reason: 'Measured search demand matches current inventory but no meaningful landing experience was observed.' })) }

export function clusterSearchQuery(query = '') { const q = norm(query); if (/finance|financing|credit|payment/.test(q)) return 'finance'; if (/trade|trade-in/.test(q)) return 'trade'; if (/service|repair|brake|maintenance|oil/.test(q)) return 'service'; if (/parts?/.test(q)) return 'parts'; if (/used|pre-owned|inventory|for sale/.test(q)) return 'used_inventory'; if (/new/.test(q)) return 'new_inventory'; if (/\b(?:near|in)\b/.test(q)) return 'location'; return 'informational' }

export function mapVdpSearchPerformance(pages = [], vdpUrls = []) { const urls = new Set(vdpUrls); return pages.filter(row => urls.has(row.page)).map(row => ({ ...row, pageType: 'vdp', status: row.status || null, evidence: { sourceType: 'search_console', sourceUrl: row.page, measuredAt: new Date().toISOString(), rawValue: row, verified: true } })) }

export function searchScore(checks = []) { const applicable = checks.filter(c => c.applicable !== false); const measured = applicable.filter(c => ['pass', 'fail'].includes(c.status)); const passed = measured.filter(c => c.status === 'pass').length; return { qualityScore: measured.length ? Math.round(passed / measured.length * 100) : null, evidenceCoverage: applicable.length ? Math.round(measured.length / applicable.length * 100) : 100, weights: SEARCH_WEIGHTS, verified100: measured.length === applicable.length && passed === applicable.length } }

export function createSearchImpactRecord(recommendationId, baselineMetrics, appliedAt = new Date().toISOString()) { return { id: `impact_${crypto.randomBytes(5).toString('hex')}`, recommendationId, appliedAt, baselineMetrics, postChangeMetrics: null, comparisonStatus: 'waiting_for_data' } }
