const n = value => value == null || value === '' ? null : Number.isFinite(Number(value)) ? Number(value) : null

export const SXO_EVENT_TYPES = Object.freeze(['page_view', 'landing_page_view', 'srp_view', 'vdp_view', 'vehicle_compare', 'finance_cta', 'trade_cta', 'service_cta', 'phone_click', 'directions_click', 'form_started', 'form_submitted', 'chat_started', 'chat_qualified', 'lead_created', 'appointment_created', 'appointment_showed', 'opportunity_created', 'deal_created', 'deal_sold', 'vehicle_delivered', 'service_appointment', 'repair_order_created'])

export function normalizeSxoEvent(event = {}) { const eventType = event.eventType || event.event_name; if (!SXO_EVENT_TYPES.includes(eventType)) throw new Error('Unsupported SXO event type'); return { dealershipId: event.dealershipId || event.dealership_id || null, occurredAt: event.occurredAt || event.created_at || new Date().toISOString(), anonymousSessionId: event.anonymousSessionId || event.payload?.anonymousSessionId || null, contactId: event.contactId || event.contact_id || null, opportunityId: event.opportunityId || event.opportunity_id || null, dealId: event.dealId || event.deal_id || null, inventoryId: event.inventoryId || event.inventory_id || null, vin: event.vin || null, pageUrl: event.pageUrl || event.payload?.pageUrl || null, referrer: event.referrer || event.payload?.referrer || null, source: event.source || event.payload?.source || null, medium: event.medium || event.payload?.medium || null, campaign: event.campaign || event.payload?.campaign || null, query: event.query || event.payload?.query || null, device: event.device || event.payload?.device || null, eventType, metadata: event.metadata || event.payload || {} } }

export function classifySource({ source, medium, referrer, pageUrl } = {}) { const raw = `${source || ''} ${medium || ''} ${referrer || ''}`.toLowerCase(); if (/google.*business|gbp|maps/.test(raw)) return 'google_business_profile'; if (/google|bing|yahoo/.test(raw) && /organic|search/.test(raw)) return raw.includes('bing') ? 'bing_organic' : 'google_organic'; if (/chatgpt|openai|perplexity|claude|copilot|\bai\b/.test(raw)) return 'ai_search'; if (/facebook|instagram|tiktok|linkedin/.test(raw)) return /paid|cpc/.test(raw) ? 'paid_social' : 'organic_social'; if (/cpc|ppc|paid/.test(raw)) return 'paid_search'; if (/email/.test(raw)) return 'email'; if (/sms/.test(raw)) return 'sms'; if (/marketplace/.test(raw)) return 'marketplace'; if (referrer && pageUrl && (() => { try { return new URL(referrer).hostname !== new URL(pageUrl).hostname } catch { return false } })()) return 'referral'; if (!source && !medium && !referrer) return 'direct'; return 'unknown' }

export function stitchFirstPartySession(events = [], { sessionId, contactId, dealershipId } = {}) { if (!sessionId || !contactId) return { linked: [], status: 'unknown', confidence: null, source: 'first_party_session' }; const eligible = events.filter(event => event.anonymousSessionId === sessionId && event.dealershipId === dealershipId && !event.contactId); return { linked: eligible.map(event => ({ ...event, contactId })), status: 'linked', confidence: 'high', source: 'first_party_session' } }

export function attributionForEvents(events = [], model = 'assisted') { const grouped = events.filter(event => event.contactId || event.dealId); const byContact = new Map(); for (const event of grouped) { const key = event.contactId || event.dealId; const list = byContact.get(key) || []; list.push(event); byContact.set(key, list) } const rows = []; for (const [identity, touches] of byContact) { const ordered = touches.slice().sort((a, b) => Date.parse(a.occurredAt) - Date.parse(b.occurredAt)); const classified = ordered.map(event => ({ ...event, classifiedSource: classifySource(event) })); if (model === 'first_touch') rows.push({ identity, source: classified[0]?.classifiedSource || 'unknown', confidence: classified[0] ? 'high' : 'unknown', method: model }); else if (model === 'last_touch') rows.push({ identity, source: classified.at(-1)?.classifiedSource || 'unknown', confidence: classified.at(-1) ? 'high' : 'unknown', method: model }); else rows.push({ identity, touches: classified.map(event => event.classifiedSource), confidence: classified.length ? 'high' : 'unknown', method: 'assisted' }); } return rows }

export function funnelFromEvents(events = []) { const counts = Object.fromEntries(['landing_page_view', 'srp_view', 'vdp_view', 'form_started', 'lead_created', 'appointment_created', 'appointment_showed', 'deal_sold', 'vehicle_delivered', 'service_appointment', 'repair_order_created'].map(stage => [stage, events.filter(event => event.eventType === stage).length])); return Object.fromEntries(Object.entries(counts).map(([stage, count]) => [stage, { count, status: 'measured' }])); }

export function conversionRate(numerator, denominator) { const a = n(numerator); const b = n(denominator); return b > 0 && a != null ? { rate: Math.round(a / b * 1000) / 10, numerator: a, denominator: b, status: 'measured' } : { rate: null, numerator: a, denominator: b, status: 'unknown' } }

export function roiSummary({ events = [], attributedGross = null, currency = 'CAD' } = {}) { const funnel = funnelFromEvents(events); const count = stage => funnel[stage]?.count || 0; const optional = stage => count(stage) > 0 ? count(stage) : null; return { visitors: optional('landing_page_view'), leads: optional('lead_created'), appointments: optional('appointment_created'), sold: optional('deal_sold'), attributedGross: n(attributedGross), currency, status: n(attributedGross) == null ? 'not_measured' : 'measured', evidence: { visitors: optional('landing_page_view') == null ? 'unavailable' : 'direct_event', leads: optional('lead_created') == null ? 'unavailable' : 'direct_event', appointments: optional('appointment_created') == null ? 'unavailable' : 'direct_event', sold: optional('deal_sold') == null ? 'unavailable' : 'direct_event', attributedGross: n(attributedGross) == null ? 'unavailable' : 'canonical_accounting' }, attributionMethod: 'assisted' } }

export function sxoQuality(checks = []) { const applicable = checks.filter(check => check.applicable !== false); const measured = applicable.filter(check => ['pass', 'fail'].includes(check.status)); const passed = measured.filter(check => check.status === 'pass').length; return { qualityScore: measured.length ? Math.round(passed / measured.length * 100) : null, evidenceCoverage: applicable.length ? Math.round(measured.length / applicable.length * 100) : 100, verified100: measured.length === applicable.length && passed === applicable.length } }

export function prioritizeSxoRecommendation(item = {}) { const traffic = n(item.impressions) || n(item.sessions) || 0; const leads = n(item.leads) || 0; const gross = n(item.attributedGross) || 0; return { ...item, priorityScore: Math.round(traffic + leads * 100 + gross / 100), evidence: { traffic: traffic > 0 ? 'measured' : 'unavailable', leads: leads > 0 ? 'measured' : 'unavailable', gross: gross > 0 ? 'canonical' : 'unavailable' } } }
